/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppPartiesRouteImport } from './routes/_app/parties'
import { Route as AppMasterRouteImport } from './routes/_app/master'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppCashFlowRouteImport } from './routes/_app/cash-flow'
import { Route as AppBanksRouteImport } from './routes/_app/banks'
import { Route as AppAuditLogRouteImport } from './routes/_app/audit-log'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterRoute = AppMasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppCashFlowRoute = AppCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppBanksRoute = AppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-log': typeof AppAuditLogRoute
  '/banks': typeof AppBanksRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/master': typeof AppMasterRoute
  '/parties': typeof AppPartiesRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-log': typeof AppAuditLogRoute
  '/banks': typeof AppBanksRoute
  '/cash-flow': typeof AppCashFlowRoute
  '/expenses': typeof AppExpensesRoute
  '/inventory': typeof AppInventoryRoute
  '/master': typeof AppMasterRoute
  '/parties': typeof AppPartiesRoute
  '/purchases': typeof AppPurchasesRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/': typeof AppIndexRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit-log': typeof AppAuditLogRoute
  '/_app/banks': typeof AppBanksRoute
  '/_app/cash-flow': typeof AppCashFlowRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/master': typeof AppMasterRoute
  '/_app/parties': typeof AppPartiesRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/analytics'
    | '/audit-log'
    | '/banks'
    | '/cash-flow'
    | '/expenses'
    | '/inventory'
    | '/master'
    | '/parties'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/api/public/bootstrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/analytics'
    | '/audit-log'
    | '/banks'
    | '/cash-flow'
    | '/expenses'
    | '/inventory'
    | '/master'
    | '/parties'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/'
    | '/api/public/bootstrap'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/analytics'
    | '/_app/audit-log'
    | '/_app/banks'
    | '/_app/cash-flow'
    | '/_app/expenses'
    | '/_app/inventory'
    | '/_app/master'
    | '/_app/parties'
    | '/_app/purchases'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/'
    | '/api/public/bootstrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master': {
      id: '/_app/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AppMasterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-flow': {
      id: '/_app/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AppCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banks': {
      id: '/_app/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AppBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-log': {
      id: '/_app/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppBanksRoute: typeof AppBanksRoute
  AppCashFlowRoute: typeof AppCashFlowRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMasterRoute: typeof AppMasterRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditLogRoute: AppAuditLogRoute,
  AppBanksRoute: AppBanksRoute,
  AppCashFlowRoute: AppCashFlowRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMasterRoute: AppMasterRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
